---       
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: cars-api-auth-policy
  namespace: default
spec:
  targets:
  - name: cars-api
  peers:
  - mtls: {}
  origins:
  - jwt:
      audiences:
      - cars-web
      issuer: "http://192.168.56.3:31275/auth/realms/istio"
      jwksUri: "http://192.168.56.3:31275/auth/realms/istio/protocol/openid-connect/certs"
  principalBinding: USE_ORIGIN